[package]
name = "model_transform"
version = "0.1.0"
authors = ["phooky <phooky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.8.0"
stl_io = "0.5.2"
glam="0.19.0"
tempfile="3"

